DATA_PATH : "../data/baby_recipes_cleaned.csv"
GROQ_CLIENT : Groq(api_key=os.getenv("GROQ_API_KEY"))
QD_CLIENT : QdrantClient("http://localhost:6333")
MODEL : 'BAAI/bge-small-en'
EMBEDDING_DIMENSIONALITY : 384
COLLECTION_NAME : "recipe_database"
