# docker/prometheus.yml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'babyfood_app'
    static_configs:
      - targets: ['app:5000']
